/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "armwar.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#    error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(armwar_CommandResponse, armwar_CommandResponse, AUTO)

PB_BIND(armwar_ArmState, armwar_ArmState, AUTO)

PB_BIND(armwar_ArmAvailability, armwar_ArmAvailability, AUTO)

PB_BIND(armwar_Connect, armwar_Connect, AUTO)

PB_BIND(armwar_Disconnect, armwar_Disconnect, AUTO)

PB_BIND(armwar_TimedCommand, armwar_TimedCommand, AUTO)

PB_BIND(armwar_TimedCommandSequence, armwar_TimedCommandSequence, AUTO)

PB_BIND(armwar_StatedCommand, armwar_StatedCommand, AUTO)

PB_BIND(armwar_SpannedCommand, armwar_SpannedCommand, AUTO)

PB_BIND(armwar_SpannedCommandSequence, armwar_SpannedCommandSequence, AUTO)

PB_BIND(armwar_ArmCommand, armwar_ArmCommand, AUTO)
