name: pre-commit
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with: 
          python-versions: "3.10"
          cache: "pip"
      - run: pip install pre-commit
      - uses: pre-commit/actions@v3.0.0
